Phase1
iamamonkeyman/ssp pull request #1
Opened 2018-08-27 09:05 UTC by iamamonkeyman

fibonacci

2018-08-29 21:52 UTC, archick12 requested changes
Please, remove unnecessary files

2018-08-29 21:52 UTC, archick12 commented on fibo/venv_venus/Scripts/activate.bat
> +@echo off
why do you need this file?

2018-08-30 07:46 UTC, iamamonkeyman commented
@archick12 hi!
just removed all not needed files

2018-08-30 07:54 UTC, archick12 approved these changes

2018-08-30 07:54 UTC, merged